### ISSUE TITLE
Connector does not work with Spark 2.2

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#51]
Note, the connector currently does not work with Spark 2.2.  We will need to update the pom.xml and add to the releases folder the bits specific to Spark 2.2.

**Comment by dennyglee** [comment]
Currently running into compilation issues 
```
[ERROR] /Users/dennylee/github/azure-cosmosdb-spark/src/main/scala/com/microsoft/azure/cosmosdb/spark/schema/CosmosDBSchema.scala:112: value findTightestCommonTypeOfTwo is not a member of object org.apache.spark.sql.catalyst.analysis.TypeCoercion
[ERROR]     TypeCoercion.findTightestCommonTypeOfTwo(t1, t2) match {
[ERROR]                  ^
[ERROR] /Users/dennylee/github/azure-cosmosdb-spark/src/main/scala/com/microsoft/azure/cosmosdb/spark/schema/CosmosDBSchema.scala:113: type mismatch;
 found   : Any
 required: org.apache.spark.sql.types.DataType
[ERROR]       case Some(commonType) => commonType
[ERROR]                                ^
[ERROR] /Users/dennylee/github/azure-cosmosdb-spark/src/main/scala/com/microsoft/azure/cosmosdb/spark/schema/InferSchema.scala:126: value findTightestCommonTypeOfTwo is not a member of object org.apache.spark.sql.catalyst.analysis.TypeCoercion
[ERROR]     TypeCoercion.findTightestCommonTypeOfTwo(t1, t2).getOrElse {
[ERROR]                  ^
[ERROR] three errors found
``` 
Will need to update the three files referring to `findTightestCommonTypeOfTwo`
