### ISSUE TITLE
`mvn clean package` fails with missing gremlin artifacts

### ISSUE THREAD

**Issue by dp-farm** [Azure/azure-cosmosdb-spark#48]
```bash
ubuntu@devesh-170:~/hadoop_experiment/azure-cosmosdb-spark$ mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building azure-cosmosdb-spark 0.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.tinkerpop:spark-gremlin:jar:3.3.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.tinkerpop:tinkergraph-gremlin:jar:3.3.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.327s
[INFO] Finished at: Tue Jul 11 12:45:13 PDT 2017
[INFO] Final Memory: 14M/173M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project azure-cosmosdb-spark: Could not resolve dependencies for project com.microsoft.azure:azure-cosmosdb-spark:jar:0.0.3-SNAPSHOT: The following artifacts could not be resolved: org.apache.tinkerpop:spark-gremlin:jar:3.3.0-SNAPSHOT, org.apache.tinkerpop:tinkergraph-gremlin:jar:3.3.0-SNAPSHOT: Could not find artifact org.apache.tinkerpop:spark-gremlin:jar:3.3.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by dennyglee** [comment]
This is because the pom.xml currently points to tinkerpop.version = 3.3.0-SNAPSHOT.  Please change this to 3.2.5.  Will be running a PR for this fix shortly.

**Comment by dp-farm** [comment]
thanks Denny,

Now it fails here -->
```
Downloaded: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar (5434 KB at 372.3 KB/sec)
[INFO] Using incremental compilation
[INFO] 'compiler-interface' not yet compiled for Scala 2.11.8. Compiling...
[INFO]   Compilation completed in 27.972 s
[INFO] Compiling 29 Scala sources and 2 Java sources to /home/ubuntu/hadoop_experiment/azure-cosmosdb-spark/target/classes...
[ERROR] /home/ubuntu/hadoop_experiment/azure-cosmosdb-spark/src/main/scala/com/microsoft/azure/cosmosdb/spark/CosmosDBSpark.scala:26: object function is not a member of package java.util
[ERROR] import java.util.function.Consumer
[ERROR]                  ^
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:06.854s
[INFO] Finished at: Wed Jul 12 09:47:49 PDT 2017
[INFO] Final Memory: 31M/420M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile) on project azure-cosmosdb-spark: Execution scala-compile of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by khdang** [comment]
@dp-farm since the introduction of gremlin dependencies, the connector is using a few features from Java 1.8. Can you recompile with Java 1.8?

**Comment by khdang** [comment]
I'm closing this - please reopen if you need further help on this.
